framework:
  messenger:
    routing:
      # Domain Events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeAddedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeCreditedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDebitedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDeletedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRenamedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeReplayedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRewoundDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeTargetedAmountChangedDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeNameRegisteredDomainEvent': domain_events
      'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeNameReleasedDomainEvent': domain_events
      # Notification Events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeAddedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeCreditedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeDebitedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeDeletedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeRenamedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeReplayedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeRewoundNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeTargetedAmountChangedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeCurrencyChangedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeLedgerDebitEntryAddedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeLedgerCreditEntryAddedNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeLedgerEntriesRewoundNotificationEvent': notification_events
      'App\BudgetEnvelopeContext\Infrastructure\Events\Notifications\BudgetEnvelopeLedgerEntriesReplayedNotificationEvent': notification_events