budget_envelope_routes:
  resource:
    path: ../BudgetEnvelope/Presentation/HTTP/Controllers/
    namespace: App\Gateway\BudgetEnvelope\Presentation\HTTP\Controllers
  type: attribute

budget_plan_routes:
  resource:
    path: ../BudgetPlan/Presentation/HTTP/Controllers/
    namespace: App\Gateway\BudgetPlan\Presentation\HTTP\Controllers
  type: attribute

user_routes:
  resource:
    path: ../User/Presentation/HTTP/Controllers/
    namespace: App\Gateway\User\Presentation\HTTP\Controllers
  type: attribute
