parameters:
  MOBILE_APP_SCHEME: '%env(MOBILE_APP_SCHEME)%'
  FRONTEND_URL: '%env(FRONTEND_URL)%'

services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Gateway\User\Presentation\HTTP\Controllers\:
    resource: '../User/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']

  App\Gateway\BudgetEnvelope\Presentation\HTTP\Controllers\:
    resource: '../BudgetEnvelope/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']

  App\Gateway\BudgetPlan\Presentation\HTTP\Controllers\:
    resource: '../BudgetPlan/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']

  App\Gateway\BudgetEnvelope\Presentation\Cli\:
    resource: '../../Gateway/BudgetEnvelope/Presentation/Cli/'
    tags: [ 'console.command' ]

  App\Gateway\BudgetEnvelope\Projections\:
    resource: '../BudgetEnvelope/Projections/'
    tags: [ 'messenger.message_handler' ]
    public: true

  App\Gateway\BudgetPlan\Projections\:
    resource: '../BudgetPlan/Projections/'
    tags: [ 'messenger.message_handler' ]
    public: true

  App\Gateway\User\Projections\:
    resource: '../User/Projections/'
    tags: [ 'messenger.message_handler' ]
    public: true
