services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Gateway\User\Presentation\HTTP\Controllers\:
    resource: '../User/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']

  App\Gateway\BudgetEnvelope\Presentation\HTTP\Controllers\:
    resource: '../BudgetEnvelope/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']

  App\Gateway\BudgetPlan\Presentation\HTTP\Controllers\:
    resource: '../BudgetPlan/Presentation/HTTP/Controllers'
    tags: ['controller.service_arguments']
