services:
  frontend:
    image: node:23
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    networks:
      - my_network

volumes:
  node_modules:

networks:
  my_network:
    driver: bridge
