fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        envelope:
            index_name: envelope_%kernel.environment%
            persistence:
                driver: orm
                model: App\Domain\Envelope\Entity\Envelope
                listener:
                    insert: true
                    update: true
                    delete: true
            properties:
                id:
                    type: integer
                createdAt:
                    type: date
                updatedAt:
                    type: date
                createdBy:
                    type: keyword
                updatedBy:
                    type: keyword
                currentBudget:
                    type: float
                targetBudget:
                    type: float
                title:
                    type: keyword
                user:
                    type: object
                    properties:
                        id:
                            type: integer
                parent:
                    type: object
                    properties:
                        id:
                            type: integer
                children:
                    type: nested
                    properties:
                        id:
                            type: integer
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        createdBy:
                            type: keyword
                        updatedBy:
                            type: keyword
                        currentBudget:
                            type: float
                        targetBudget:
                            type: float
                        title:
                            type: keyword
                        parent:
                            type: object
                            properties:
                                id:
                                    type: integer
        user:
            index_name: user_%kernel.environment%
            persistence:
                driver: orm
                model: App\Domain\User\Entity\User
                listener:
                    insert: true
                    update: true
                    delete: true
            properties:
                id:
                    type: integer
                email:
                    type: keyword
                password:
                    type: keyword
                firstname:
                    type: text
                lastname:
                    type: text
                consentGiven:
                    type: boolean
                consentDate:
                    type: date
                roles:
                    type: keyword
                createdAt:
                    type: date
                updatedAt:
                    type: date
                passwordResetToken:
                    type: keyword
                passwordResetTokenExpiry:
                    type: date
                envelopes:
                    type: nested
                    properties:
                        id:
                            type: integer
                        createdAt:
                            type: date
                        updatedAt:
                            type: date
                        createdBy:
                            type: keyword
                        updatedBy:
                            type: keyword
                        currentBudget:
                            type: float
                        targetBudget:
                            type: float
                        title:
                            type: keyword
                        parent:
                            type: object
                            properties:
                                id:
                                    type: integer
                        children:
                            type: nested
                            properties:
                                id:
                                    type: integer
                                createdAt:
                                    type: date
                                updatedAt:
                                    type: date
                                createdBy:
                                    type: keyword
                                updatedBy:
                                    type: keyword
                                currentBudget:
                                    type: float
                                targetBudget:
                                    type: float
                                title:
                                    type: keyword
                                parent:
                                    type: object
                                    properties:
                                        id:
                                            type: integer