fos_elastica:
    clients:
        default: { url: '%env(ELASTICSEARCH_URL)%' }
    indexes:
        user:
            index_name: user_%kernel.environment%
            persistence:
                driver: orm
                model: App\UserManagement\Infrastructure\Entity\User
                listener:
                    insert: true
                    update: true
                    delete: true
            properties:
                id:
                    type: integer
                uuid:
                    type: keyword
                email:
                    type: keyword
                password:
                    type: text
                firstname:
                    type: text
                lastname:
                    type: text
                consentGiven:
                    type: boolean
                consentDate:
                    type: date
                roles:
                    type: keyword
                createdAt:
                    type: date
                updatedAt:
                    type: date
                passwordResetToken:
                    type: keyword
                passwordResetTokenExpiry:
                    type: date