controllers_rest_envelope:
    resource:
        path: ../src/BudgetEnvelopeContext/Presentation/HTTP/Controllers/
        namespace: App\BudgetEnvelopeContext\Presentation\HTTP\Controllers
    type: attribute

controllers_rest_user:
    resource:
        path: ../src/UserContext/Presentation/HTTP/Controllers/
        namespace: App\UserContext\Presentation\HTTP\Controllers
    type: attribute

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
