controllers_rest_envelope:
    resource:
        path: ../src/Gateway/BudgetEnvelope/HTTP/Controllers/
        namespace: App\Gateway\BudgetEnvelope\HTTP\Controllers
    type: attribute

controllers_rest_user:
    resource:
        path: ../src/Gateway/User/HTTP/Controllers/
        namespace: App\Gateway\User\HTTP\Controllers
    type: attribute

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
