controllers_rest_envelope:
    resource:
        path: ../src/EnvelopeManagement/Presentation/HTTP/Controllers/
        namespace: App\EnvelopeManagement\Presentation\HTTP\Controllers
    type: attribute

controllers_rest_user:
    resource:
        path: ../src/UserManagement/Presentation/HTTP/Controllers/
        namespace: App\UserManagement\Presentation\HTTP\Controllers
    type: attribute

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
