parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UserManagement/Infrastructure/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'

    App\UserManagement\Presentation\HTTP\Controllers\:
        resource: '../src/UserManagement/Presentation/HTTP/Controllers'
        tags: [ 'controller.service_arguments' ]

    App\BudgetEnvelopeManagement\Presentation\HTTP\Controllers\:
        resource: '../src/BudgetEnvelopeManagement/Presentation/HTTP/Controllers'
        tags: [ 'controller.service_arguments' ]

    App\BudgetEnvelopeManagement\Application\Handlers\CommandHandlers\CreateABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\CommandHandlers\RenameABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\CommandHandlers\CreditABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\CommandHandlers\DebitABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\CommandHandlers\DeleteABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\QueryHandlers\GetABudgetEnvelopeWithItsHistoryQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\Application\Handlers\QueryHandlers\ListBudgetEnvelopesQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeManagement\ReadModels\Projections\BudgetEnvelopeProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\CreateUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserFirstnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserLastnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\UpdateUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\RequestUserPasswordResetCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\ResetUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\LogoutUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\Application\Handlers\CommandHandlers\DeleteUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserManagement\ReadModels\Projections\UserProjection:
        tags: [ 'messenger.message_handler' ]

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.password_hasher'

    App\SharedContext\Infrastructure\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }
