imports:
    - { resource: '../src/BudgetEnvelopeContext/Config/services.yaml' }
    - { resource: '../src/BudgetPlanContext/Config/services.yaml' }
    - { resource: '../src/UserContext/Config/services.yaml' }
    - { resource: '../src/Gateway/Config/services.yaml' }
    - { resource: '../src/SharedContext/Config/services.yaml' }
    - { resource: '../src/Libraries/FluxCapacitor/Config/services.yaml' }

parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.password_hasher'

    App\SharedContext\Infrastructure\EventListener\RequestIdListener:
        arguments:
            $requestIdProvider: '@App\Libraries\FluxCapacitor\EventStore\Services\RequestIdProvider'
        tags:
            - { name: kernel.event_subscriber }

    App\Libraries\FluxCapacitor\Anonymizer\Repositories\KeyManagementRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $passphrase: '%env(KEY_MANAGEMENT_SECRET)%'
