parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/UserContext/Infrastructure/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%env(RABBITMQ_HOST)%'
            $port: '%env(RABBITMQ_PORT)%'
            $user: '%env(RABBITMQ_USER)%'
            $password: '%env(RABBITMQ_PASSWORD)%'

    App\Gateway\User\Presentation\HTTP\Controllers\:
        resource: '../src/Gateway/User/Presentation/HTTP/Controllers'
        tags: [ 'controller.service_arguments' ]

    App\Gateway\BudgetEnvelope\Presentation\HTTP\Controllers\:
        resource: '../src/Gateway/BudgetEnvelope/Presentation/HTTP/Controllers'
        tags: [ 'controller.service_arguments' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\AddABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\RenameABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\CreditABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\DebitABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\DeleteABudgetEnvelopeCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\ReplayABudgetEnvelopeEventsCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\RewindABudgetEnvelopeFromEventsCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\ChangeABudgetEnvelopeTargetedAmountCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\CommandHandlers\ChangeABudgetEnvelopeCurrencyCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\QueryHandlers\GetABudgetEnvelopeWithItsLedgerQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\Application\Handlers\QueryHandlers\ListBudgetEnvelopesQueryHandler:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\ReadModels\Projections\BudgetEnvelopeProjection:
        tags: [ 'messenger.message_handler' ]

    App\BudgetEnvelopeContext\ReadModels\Projections\BudgetEnvelopeLedgerEntryProjection:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\SignUpAUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ChangeAUserFirstnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ChangeAUserLastnameCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ChangeAUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ChangeAUserLanguagePreferenceCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\RequestAUserPasswordResetCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ResetAUserPasswordCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\LogoutAUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\DeleteAUserCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\ReplayAUserEventsCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\Application\Handlers\CommandHandlers\RewindAUserFromEventsCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\UserContext\ReadModels\Projections\UserProjection:
        tags: [ 'messenger.message_handler' ]

    Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface:
        alias: 'security.password_hasher'

    App\SharedContext\Infrastructure\EventListener\ExceptionListener:
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.exception' }

    App\SharedContext\Infrastructure\EventListener\RequestIdListener:
        arguments:
            $requestIdProvider: '@App\Libraries\FluxCapacitor\Services\RequestIdProvider'
        tags:
            - { name: kernel.event_subscriber }

    App\Libraries\Anonymii\Repositories\KeyManagementRepository:
        arguments:
            $connection: '@doctrine.dbal.default_connection'
            $passphrase: '%env(KEY_MANAGEMENT_SECRET)%'
