services:
  symfony:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=dev
      - APP_SECRET=${APP_SECRET_PASS}
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: postgres:17.4
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      POSTGRES_DB: ${MYSQL_DATABASE}
      POSTGRES_USER: ${PMA_USER}
    ports:
      - "5432:5432"
    networks:
      - my_network

  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/public
      - ./config/certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - symfony
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
