framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: true
                middleware:
                    - validation
            event_bus:
                default_middleware: true
                middleware:
                    - validation

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: 'domain_events'
                        type: fanout

        routing:
            'App\BudgetEnvelopeManagement\Domain\Events\BudgetEnvelopeCreatedEvent': async
            'App\BudgetEnvelopeManagement\Domain\Events\BudgetEnvelopeRenamedEvent': async
            'App\BudgetEnvelopeManagement\Domain\Events\BudgetEnvelopeDebitedEvent': async
            'App\BudgetEnvelopeManagement\Domain\Events\BudgetEnvelopeDeletedEvent': async
            'App\BudgetEnvelopeManagement\Domain\Events\BudgetEnvelopeCreditedEvent': async
            'App\UserManagement\Domain\Events\UserSignedUpEvent': async
            'App\UserManagement\Domain\Events\UserFirstnameUpdatedEvent': async
            'App\UserManagement\Domain\Events\UserLastnameUpdatedEvent': async
            'App\UserManagement\Domain\Events\UserPasswordUpdatedEvent': async
            'App\UserManagement\Domain\Events\UserPasswordResetRequestedEvent': async
            'App\UserManagement\Domain\Events\UserPasswordResetEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
