imports:
    - { resource: '../../src/BudgetEnvelopeContext/Config/messenger.yaml' }
    - { resource: '../../src/BudgetPlanContext/Config/messenger.yaml' }
    - { resource: '../../src/UserContext/Config/messenger.yaml' }

framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: true
                middleware:
                    - validation
                    - 'App\Libraries\FluxCapacitor\EventStore\Middlewares\SaveAggregateMiddleware'
            event_bus:
                default_middleware: true
                middleware:
                    - validation

        transports:
            sync: 'sync://'
            domain_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: 'domain_events'
                        type: fanout
            notification_events:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: 'notification_events'
                        type: fanout

        routing:
# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
