framework:
    messenger:
        default_bus: command_bus
        buses:
            command_bus:
                default_middleware: true
                middleware:
                    - validation
            event_bus:
                default_middleware: true
                middleware:
                    - validation

        transports:
            sync: 'sync://'
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
                options:
                    exchange:
                        name: 'domain_events'
                        type: fanout

        routing:
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeCreatedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeCreditedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDebitedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDeletedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRenamedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeReplayedDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRewoundDomainEvent': async
            'App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeTargetedAmountUpdatedDomainEvent': async
            'App\UserContext\Domain\Events\UserDeletedDomainEvent': async
            'App\UserContext\Domain\Events\UserFirstnameUpdatedDomainEvent': async
            'App\UserContext\Domain\Events\UserLastnameUpdatedDomainEvent': async
            'App\UserContext\Domain\Events\UserPasswordResetDomainEvent': async
            'App\UserContext\Domain\Events\UserPasswordResetRequestedDomainEvent': async
            'App\UserContext\Domain\Events\UserPasswordUpdatedDomainEvent': async
            'App\UserContext\Domain\Events\UserSignedUpDomainEvent': async
            'App\UserContext\Domain\Events\UserReplayedDomainEvent': async
            'App\UserContext\Domain\Events\UserRewoundDomainEvent': async

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
