nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['https://gogobudgeto.expo.app', 'http://localhost:8081']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        allow_private_network: true
        max_age: 3600
    paths:
        '^/':
            allow_origin: ['https://gogobudgeto.expo.app', 'http://localhost:8081']
            allow_headers: ['Content-Type', 'Authorization', 'Request-Id']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_private_network: true
            max_age: 3600
        '^/api/':
            allow_origin: ['https://gogobudgeto.expo.app', 'http://localhost:8081']
            allow_headers: ['Content-Type', 'Authorization', 'Request-Id']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'DELETE']
            allow_private_network: true
            max_age: 3600
