services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\SharedContext\:
    resource: '../'
    exclude:
      - '../Config/'

  App\SharedContext\Infrastructure\EventListener\ExceptionListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception' }

  App\SharedContext\Infrastructure\Services\BudgetAppEventUpcastingService: ~
  
  App\Libraries\FluxCapacitor\EventStore\Ports\EventUpcastingServiceInterface:
    alias: App\SharedContext\Infrastructure\Services\BudgetAppEventUpcastingService
