services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\SharedContext\:
    resource: '../'
    exclude:
      - '../Config/'

  App\SharedContext\Infrastructure\EventListener\ExceptionListener:
    tags:
      - { name: 'kernel.event_listener', event: 'kernel.exception' }
