events:
  BudgetEnvelopeAddedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeAddedDomainEvent_v1
  BudgetEnvelopeCreditedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeCreditedDomainEvent_v1
  BudgetEnvelopeDebitedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDebitedDomainEvent_v1
  BudgetEnvelopeDeletedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeDeletedDomainEvent_v1
  BudgetEnvelopeRenamedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRenamedDomainEvent_v1
  BudgetEnvelopeReplayedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeReplayedDomainEvent_v1
  BudgetEnvelopeRewoundDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeRewoundDomainEvent_v1
  BudgetEnvelopeNameRegisteredDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeNameRegisteredDomainEvent_v1
  BudgetEnvelopeNameReleasedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeNameReleasedDomainEvent_v1
  BudgetEnvelopeTargetedAmountChangedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeTargetedAmountChangedDomainEvent_v1
  BudgetEnvelopeCurrencyChangedDomainEvent_v1: App\BudgetEnvelopeContext\Domain\Events\BudgetEnvelopeCurrencyChangedDomainEvent_v1
  BudgetPlanGeneratedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanGeneratedDomainEvent_v1
  BudgetPlanGeneratedWithOneThatAlreadyExistsDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanGeneratedWithOneThatAlreadyExistsDomainEvent_v1
  BudgetPlanIncomeAddedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanIncomeAddedDomainEvent_v1
  BudgetPlanIncomeAdjustedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanIncomeAdjustedDomainEvent_v1
  BudgetPlanIncomeRemovedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanIncomeRemovedDomainEvent_v1
  BudgetPlanNeedAddedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanNeedAddedDomainEvent_v1
  BudgetPlanNeedAdjustedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanNeedAdjustedDomainEvent_v1
  BudgetPlanNeedRemovedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanNeedRemovedDomainEvent_v1
  BudgetPlanRemovedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanRemovedDomainEvent_v1
  BudgetPlanSavingAddedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanSavingAddedDomainEvent_v1
  BudgetPlanSavingAdjustedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanSavingAdjustedDomainEvent_v1
  BudgetPlanSavingRemovedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanSavingRemovedDomainEvent_v1
  BudgetPlanWantAddedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanWantAddedDomainEvent_v1
  BudgetPlanWantAdjustedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanWantAdjustedDomainEvent_v1
  BudgetPlanWantRemovedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanWantRemovedDomainEvent_v1
  BudgetPlanDateRegisteredDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanDateRegisteredDomainEvent_v1
  BudgetPlanDateReleasedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanDateReleasedDomainEvent_v1
  BudgetPlanCurrencyChangedDomainEvent_v1: App\BudgetPlanContext\Domain\Events\BudgetPlanCurrencyChangedDomainEvent_v1
  UserDeletedDomainEvent_v1: App\UserContext\Domain\Events\UserDeletedDomainEvent_v1
  UserFirstnameChangedDomainEvent_v1: App\UserContext\Domain\Events\UserFirstnameChangedDomainEvent_v1
  UserLanguagePreferenceChangedDomainEvent_v1: App\UserContext\Domain\Events\UserLanguagePreferenceChangedDomainEvent_v1
  UserLastnameChangedDomainEvent_v1: App\UserContext\Domain\Events\UserLastnameChangedDomainEvent_v1
  UserReplayedDomainEvent_v1: App\UserContext\Domain\Events\UserReplayedDomainEvent_v1
  UserRewoundDomainEvent_v1: App\UserContext\Domain\Events\UserRewoundDomainEvent_v1
  UserSignedUpDomainEvent_v1: App\UserContext\Domain\Events\UserSignedUpDomainEvent_v1
  UserEmailRegisteredDomainEvent_v1: App\UserContext\Domain\Events\UserEmailRegisteredDomainEvent_v1
  UserEmailReleasedDomainEvent_v1: App\UserContext\Domain\Events\UserEmailReleasedDomainEvent_v1

aggregates:
  BudgetEnvelope: App\BudgetEnvelopeContext\Domain\Aggregates\BudgetEnvelope
  BudgetPlan: App\BudgetPlanContext\Domain\Aggregates\BudgetPlan
  BudgetPlanDateRegistry: App\BudgetPlanContext\Domain\Aggregates\BudgetPlanDateRegistry
  BudgetEnvelopeNameRegistry: App\BudgetEnvelopeContext\Domain\Aggregates\BudgetEnvelopeNameRegistry
  User: App\UserContext\Domain\Aggregates\User
  UserEmailRegistry: App\UserContext\Domain\Aggregates\UserEmailRegistry

event_to_aggregate:
  BudgetEnvelopeNameRegisteredDomainEvent_v1: BudgetEnvelopeNameRegistry
  BudgetEnvelopeNameReleasedDomainEvent_v1: BudgetEnvelopeNameRegistry
  BudgetEnvelopeAddedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeCreditedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeDebitedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeDeletedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeRenamedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeReplayedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeRewoundDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeTargetedAmountChangedDomainEvent_v1: BudgetEnvelope
  BudgetEnvelopeCurrencyChangedDomainEvent_v1: BudgetEnvelope
  BudgetPlanDateRegisteredDomainEvent_v1: BudgetPlanDateRegistry
  BudgetPlanDateReleasedDomainEvent_v1: BudgetPlanDateRegistry
  BudgetPlanGeneratedDomainEvent_v1: BudgetPlan
  BudgetPlanGeneratedWithOneThatAlreadyExistsDomainEvent_v1: BudgetPlan
  BudgetPlanIncomeAddedDomainEvent_v1: BudgetPlan
  BudgetPlanIncomeAdjustedDomainEvent_v1: BudgetPlan
  BudgetPlanIncomeRemovedDomainEvent_v1: BudgetPlan
  BudgetPlanNeedAddedDomainEvent_v1: BudgetPlan
  BudgetPlanNeedAdjustedDomainEvent_v1: BudgetPlan
  BudgetPlanNeedRemovedDomainEvent_v1: BudgetPlan
  BudgetPlanRemovedDomainEvent_v1: BudgetPlan
  BudgetPlanSavingAddedDomainEvent_v1: BudgetPlan
  BudgetPlanSavingAdjustedDomainEvent_v1: BudgetPlan
  BudgetPlanSavingRemovedDomainEvent_v1: BudgetPlan
  BudgetPlanWantAddedDomainEvent_v1: BudgetPlan
  BudgetPlanWantAdjustedDomainEvent_v1: BudgetPlan
  BudgetPlanWantRemovedDomainEvent_v1: BudgetPlan
  BudgetPlanCurrencyChangedDomainEvent_v1: BudgetPlan
  UserDeletedDomainEvent_v1: User
  UserFirstnameChangedDomainEvent_v1: User
  UserLanguagePreferenceChangedDomainEvent_v1: User
  UserLastnameChangedDomainEvent_v1: User
  UserReplayedDomainEvent_v1: User
  UserRewoundDomainEvent_v1: User
  UserSignedUpDomainEvent_v1: User
  UserEmailRegisteredDomainEvent_v1: UserEmailRegistry
  UserEmailReleasedDomainEvent_v1: UserEmailRegistry

projections:
  App\Gateway\BudgetEnvelope\Projections\BudgetEnvelopeProjection:
    table: budget_envelope_view
    aggregate: BudgetEnvelope
  App\Gateway\BudgetEnvelope\Projections\BudgetEnvelopeLedgerEntryProjection:
    table: budget_envelope_ledger_entry_view
    aggregate: BudgetEnvelope
  App\Gateway\User\Projections\UserProjection:
    table: user_view
    aggregate: User
  App\Gateway\BudgetPlan\Projections\BudgetPlanProjection:
    table: budget_plan_view
    aggregate: BudgetPlan
  App\Gateway\BudgetPlan\Projections\BudgetPlanIncomeEntryProjection:
    table: budget_plan_income_entry_view
    aggregate: BudgetPlan
  App\Gateway\BudgetPlan\Projections\BudgetPlanNeedEntryProjection:
    table: budget_plan_need_entry_view
    aggregate: BudgetPlan
  App\Gateway\BudgetPlan\Projections\BudgetPlanSavingEntryProjection:
    table: budget_plan_saving_entry_view
    aggregate: BudgetPlan
  App\Gateway\BudgetPlan\Projections\BudgetPlanWantEntryProjection:
    table: budget_plan_want_entry_view
    aggregate: BudgetPlan
