doctrine:
  orm:
    mappings:
      BudgetPlanView:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/BudgetPlanContext/ReadModels/Views'
        prefix: 'App\BudgetPlanContext\ReadModels\Views'
        alias: BudgetPlanView
