doctrine:
  orm:
    mappings:
      UserOAuth:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/UserContext/Domain/Entities'
        prefix: 'App\UserContext\Domain\Entities'
        alias: UserOAuth
      RefreshToken:
        type: attribute
        is_bundle: false
        dir: '%kernel.project_dir%/src/UserContext/Infrastructure/Entities'
        prefix: 'App\UserContext\Infrastructure\Entities'
        alias: RefreshToken