controllers_rest_envelope:
    resource:
        path: ../src/EnvelopeManagement/UI/Http/Rest/Envelope/Controller/
        namespace: App\EnvelopeManagement\UI\Http\Rest\Envelope\Controller
    type: attribute

controllers_rest_user:
    resource:
        path: ../src/UserManagement/UI/Http/Rest/User/Controller/
        namespace: App\UserManagement\UI\Http\Rest\User\Controller
    type: attribute

api_login_check:
    path: /api/login_check

api_refresh_token:
    path: /api/token/refresh
